version: '3.8'

services:
  mongo:
    image: mongo:8.0-rc
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - MoviesAPI-MongoDB
      - MongoDB-MongoExpress
    volumes:
      - mongo-data:/data/db 

  mongo-express:
    image: mongo-express:1.0-20-alpine3.19
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
    ports:
      - '8081:8081'
    networks:
      - MongoDB-MongoExpress

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - Redis-MoviesAPI

  movies-api:
    image: doconnor/movies-api:1.0
    container_name: movies-api
    ports:
      - '9000:9000'
    environment:
      MONGODB_URI: mongodb://admin:password@mongo:27017
      REDIS_URI: redis://redis:6379
      ENABLE_WRITING_HANDLERS: 'false'
    depends_on:
      - mongo
      - redis
    networks:
      - Redis-MoviesAPI
      - MoviesAPI-MongoDB

  seed:
    image: node:current-alpine
    container_name: seed
    depends_on:
      - mongo
    volumes:
      - .:/app
    working_dir: /app
    command: ["node", "seed.js"]
    environment:
      MONGODB_URI: mongodb://admin:password@mongo:27017
    networks:
      - MoviesAPI-MongoDB

networks:
  Redis-MoviesAPI:
    driver: bridge
  MoviesAPI-MongoDB:
    driver: bridge
  MongoDB-MongoExpress:
    driver: bridge

volumes:
  mongo-data:
